title: Bast
description: A structured Go framework for building efficient, scalable, and production server-side applications.
theme: just-the-docs

url: "https://bastion-framework.github.io"
baseurl: "/bast"

aux_links:
  "GitHub":
    - "https://github.com/bastion-framework/bast"

aux_links_new_tab: true

footer_content: "Author <a href=\"https://github.com/kasimlyee\">Kasim Lyee</a> &middot; SUDs Tech &middot; MIT License"

color_scheme: dark

search_enabled: true
search_tokenizer_separator: /[\s/]+/

nav_sort: order

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
